{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[2024-10-24 19:36:21,304 cli INFO] \n",
      "##############################################\n",
      "#                                            #\n",
      "#                 HADDOCK3                   #\n",
      "#                                            #\n",
      "##############################################\n",
      "\n",
      "!! Some of the HADDOCK3 components use CNS (Crystallographic and NMR System) which is free of use for non-profit applications. !!\n",
      "!! For commercial use it is your own responsibility to have a proper license. !!\n",
      "!! For details refer to the DISCLAIMER file in the HADDOCK3 repository. !!\n",
      "\n",
      "Starting HADDOCK3 v2024.10.0b6 on 2024-10-24 19:36:00\n",
      "\n",
      "Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]\n",
      "\n",
      "[2024-10-24 19:36:33,244 libworkflow INFO] Reading instructions step 0_topoaa\n",
      "[2024-10-24 19:36:33,246 libworkflow INFO] Reading instructions step 1_rigidbody\n",
      "[2024-10-24 19:36:33,247 libworkflow INFO] Reading instructions step 2_caprieval\n",
      "[2024-10-24 19:36:33,248 libworkflow INFO] Reading instructions step 3_flexref\n",
      "[2024-10-24 19:36:33,250 libworkflow INFO] Reading instructions step 4_caprieval\n",
      "[2024-10-24 19:36:33,251 libworkflow INFO] Reading instructions step 5_emref\n",
      "[2024-10-24 19:36:33,252 libworkflow INFO] Reading instructions step 6_clustfcc\n",
      "[2024-10-24 19:36:33,253 libworkflow INFO] Reading instructions step 7_caprieval\n",
      "[2024-10-24 19:36:33,300 base_cns_module INFO] Running [topoaa] module\n",
      "[2024-10-24 19:36:33,301 __init__ INFO] [topoaa] Molecule 1: rf_design_0.pdb\n",
      "[2024-10-24 19:36:33,305 __init__ INFO] [topoaa] Sanitizing molecule rf_design_0_1.pdb\n",
      "[2024-10-24 19:36:33,312 __init__ INFO] [topoaa] Topology CNS input created\n",
      "[2024-10-24 19:36:33,313 __init__ INFO] [topoaa] Molecule 2: 8hgo.pdb\n",
      "[2024-10-24 19:36:33,328 __init__ INFO] [topoaa] Sanitizing molecule 8hgo.pdb\n",
      "[2024-10-24 19:36:33,381 __init__ INFO] [topoaa] Topology CNS input created\n",
      "[2024-10-24 19:36:33,382 __init__ INFO] [topoaa] Running CNS Jobs n=2\n",
      "[2024-10-24 19:36:33,383 libutil INFO] Selected 2 cores to process 2 jobs, with 56 maximum available cores.\n",
      "[2024-10-24 19:36:33,388 libparallel INFO] Using 2 cores\n",
      "[2024-10-24 19:37:05,060 libparallel INFO] 2 tasks finished\n",
      "[2024-10-24 19:37:05,063 __init__ INFO] [topoaa] CNS jobs have finished\n",
      "[2024-10-24 19:37:05,068 base_cns_module INFO] Module [topoaa] finished.\n",
      "[2024-10-24 19:37:05,069 __init__ INFO] [topoaa] took 32 seconds\n",
      "[2024-10-24 19:37:06,222 base_cns_module INFO] Running [rigidbody] module\n",
      "[2024-10-24 19:37:06,225 __init__ INFO] [rigidbody] crossdock=true\n",
      "[2024-10-24 19:37:06,226 __init__ INFO] [rigidbody] Preparing jobs...\n",
      "[2024-10-24 19:37:06,226 libutil INFO] Selected 20 cores to process 20 jobs, with 56 maximum available cores.\n",
      "[2024-10-24 19:37:06,228 libparallel INFO] Using 20 cores\n",
      "[2024-10-24 19:37:06,265 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,272 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,282 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,292 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,301 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,313 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,322 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,333 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,341 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,356 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,366 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,375 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,395 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,404 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,414 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,423 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,432 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,448 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,459 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,468 libparallel WARNING] Exception in task execution: Chain/seg IDs are not unique for pdbs ([pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/rf_design_0_1_haddock.pdb, [pdb|2024-10-24 19:37:05] /home/mubale/functional_eval/docking/run_test/0_topoaa/8hgo_haddock.pdb).\n",
      "[2024-10-24 19:37:06,482 libparallel INFO] 20 tasks finished\n",
      "[2024-10-24 19:37:06,485 __init__ INFO] [rigidbody] Preparation took 0.259861 seconds\n",
      "[2024-10-24 19:37:06,489 __init__ INFO] [rigidbody] Running CNS Jobs n=20\n",
      "[2024-10-24 19:37:06,490 libutil INFO] Selected 20 cores to process 20 jobs, with 56 maximum available cores.\n",
      "[2024-10-24 19:37:06,494 libparallel INFO] Using 20 cores\n",
      "[2024-10-24 19:37:06,506 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,516 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,531 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,542 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,555 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,567 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,581 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,593 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,605 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,615 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,625 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,638 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,650 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,662 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,673 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,682 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,693 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,708 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,720 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,731 libparallel WARNING] Exception in task execution: local variable 'error' referenced before assignment\n",
      "[2024-10-24 19:37:06,743 libparallel INFO] 20 tasks finished\n",
      "[2024-10-24 19:37:06,746 __init__ INFO] [rigidbody] CNS jobs have finished\n",
      "[2024-10-24 19:37:06,753 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 20.00%.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mubale/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/libs/libutil.py\", line 335, in log_error_and_exit\n",
      "    yield\n",
      "  File \"/home/mubale/functional_eval/docking/haddock3/src/haddock/clis/cli.py\", line 195, in main\n",
      "    workflow.run()\n",
      "  File \"/home/mubale/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/libs/libworkflow.py\", line 43, in run\n",
      "    step.execute()\n",
      "  File \"/home/mubale/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/libs/libworkflow.py\", line 162, in execute\n",
      "    self.module.run()  # type: ignore\n",
      "  File \"/home/mubale/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/modules/base_cns_module.py\", line 61, in run\n",
      "    self._run()\n",
      "  File \"/home/mubale/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/modules/sampling/rigidbody/__init__.py\", line 248, in _run\n",
      "    self.export_io_models(faulty_tolerance=self.params[\"tolerance\"])\n",
      "  File \"/home/mubale/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/modules/__init__.py\", line 309, in export_io_models\n",
      "    self.finish_with_error(_msg)\n",
      "  File \"/home/mubale/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/modules/__init__.py\", line 317, in finish_with_error\n",
      "    raise RuntimeError(reason)\n",
      "RuntimeError: 100.00% of output was not generated for this module and tolerance was set to 20.00%.\n",
      "[2024-10-24 19:37:06,756 libutil ERROR] 100.00% of output was not generated for this module and tolerance was set to 20.00%.\n",
      "[2024-10-24 19:37:06,757 libutil ERROR] An error has occurred, see log file. And contact the developers if needed.\n",
      "[2024-10-24 19:37:06,758 libutil INFO] Finished at 24/10/2024 19:37:06. For any help contact us at https://github.com/haddocking/haddock3/issues. Agur! La revedere! 再见!.\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'tuple' object has no attribute 'tb_frame'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/libs/libutil.py:335\u001b[0m, in \u001b[0;36mlog_error_and_exit\u001b[0;34m()\u001b[0m\n\u001b[1;32m    334\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 335\u001b[0m     \u001b[38;5;28;01myield\u001b[39;00m\n\u001b[1;32m    336\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m err:\n",
      "File \u001b[0;32m~/functional_eval/docking/haddock3/src/haddock/clis/cli.py:195\u001b[0m, in \u001b[0;36mmain\u001b[0;34m(workflow, restart, extend_run, setup_only, log_level)\u001b[0m\n\u001b[1;32m    194\u001b[0m \u001b[38;5;66;03m# Main loop of execution\u001b[39;00m\n\u001b[0;32m--> 195\u001b[0m \u001b[43mworkflow\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    196\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m other_params[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpostprocess\u001b[39m\u001b[38;5;124m\"\u001b[39m]:\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/libs/libworkflow.py:43\u001b[0m, in \u001b[0;36mWorkflowManager.run\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     42\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m---> 43\u001b[0m     \u001b[43mstep\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     44\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m HaddockTermination:\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/libs/libworkflow.py:162\u001b[0m, in \u001b[0;36mStep.execute\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    161\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmodule\u001b[38;5;241m.\u001b[39msave_config(Path(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mworking_path, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mparams.cfg\u001b[39m\u001b[38;5;124m\"\u001b[39m))  \u001b[38;5;66;03m# type: ignore\u001b[39;00m\n\u001b[0;32m--> 162\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmodule\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m  \u001b[38;5;66;03m# type: ignore\u001b[39;00m\n\u001b[1;32m    163\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyboardInterrupt\u001b[39;00m:\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/modules/base_cns_module.py:61\u001b[0m, in \u001b[0;36mBaseCNSModule.run\u001b[0;34m(self, **params)\u001b[0m\n\u001b[1;32m     60\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m working_directory(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpath):\n\u001b[0;32m---> 61\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_run\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     63\u001b[0m log\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mModule [\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mname\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m] finished.\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/modules/sampling/rigidbody/__init__.py:248\u001b[0m, in \u001b[0;36mHaddockModule._run\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    246\u001b[0m         model\u001b[38;5;241m.\u001b[39mscore \u001b[38;5;241m=\u001b[39m haddock_score\n\u001b[0;32m--> 248\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexport_io_models\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfaulty_tolerance\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mparams\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mtolerance\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/modules/__init__.py:309\u001b[0m, in \u001b[0;36mBaseHaddockModule.export_io_models\u001b[0;34m(self, faulty_tolerance)\u001b[0m\n\u001b[1;32m    308\u001b[0m \u001b[38;5;66;03m# Show final error message\u001b[39;00m\n\u001b[0;32m--> 309\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfinish_with_error\u001b[49m\u001b[43m(\u001b[49m\u001b[43m_msg\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/modules/__init__.py:317\u001b[0m, in \u001b[0;36mBaseHaddockModule.finish_with_error\u001b[0;34m(self, reason)\u001b[0m\n\u001b[1;32m    316\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m--> 317\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(reason)\n",
      "\u001b[0;31mRuntimeError\u001b[0m: 100.00% of output was not generated for this module and tolerance was set to 20.00%.",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mSystemExit\u001b[0m                                Traceback (most recent call last)",
      "    \u001b[0;31m[... skipping hidden 1 frame]\u001b[0m\n",
      "Cell \u001b[0;32mIn[2], line 13\u001b[0m\n\u001b[1;32m     12\u001b[0m cfg \u001b[38;5;241m=\u001b[39m build_config(out_dir, config_file, ambig_file, molecules, motif_specs, residue_specs)\n\u001b[0;32m---> 13\u001b[0m \u001b[43mcli\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmain\u001b[49m\u001b[43m(\u001b[49m\u001b[43mworkflow\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mconfig_file\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/functional_eval/docking/haddock3/src/haddock/clis/cli.py:184\u001b[0m, in \u001b[0;36mmain\u001b[0;34m(workflow, restart, extend_run, setup_only, log_level)\u001b[0m\n\u001b[1;32m    182\u001b[0m     WorkflowManager_ \u001b[38;5;241m=\u001b[39m WorkflowManager\n\u001b[0;32m--> 184\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m (\n\u001b[1;32m    185\u001b[0m     working_directory(_run_dir),\n\u001b[1;32m    186\u001b[0m     log_error_and_exit(),\n\u001b[1;32m    187\u001b[0m ):\n\u001b[1;32m    188\u001b[0m     workflow \u001b[38;5;241m=\u001b[39m WorkflowManager_(\n\u001b[1;32m    189\u001b[0m         workflow_params\u001b[38;5;241m=\u001b[39mparams,\n\u001b[1;32m    190\u001b[0m         start\u001b[38;5;241m=\u001b[39mrestart_step,\n\u001b[1;32m    191\u001b[0m         \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mother_params,\n\u001b[1;32m    192\u001b[0m     )\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/contextlib.py:153\u001b[0m, in \u001b[0;36m_GeneratorContextManager.__exit__\u001b[0;34m(self, typ, value, traceback)\u001b[0m\n\u001b[1;32m    152\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 153\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgen\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mthrow\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtyp\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvalue\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtraceback\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    154\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[1;32m    155\u001b[0m     \u001b[38;5;66;03m# Suppress StopIteration *unless* it's the same exception that\u001b[39;00m\n\u001b[1;32m    156\u001b[0m     \u001b[38;5;66;03m# was passed to throw().  This prevents a StopIteration\u001b[39;00m\n\u001b[1;32m    157\u001b[0m     \u001b[38;5;66;03m# raised inside the \"with\" statement from being suppressed.\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/haddock/libs/libutil.py:344\u001b[0m, in \u001b[0;36mlog_error_and_exit\u001b[0;34m()\u001b[0m\n\u001b[1;32m    343\u001b[0m log\u001b[38;5;241m.\u001b[39minfo(get_goodbye_help())\n\u001b[0;32m--> 344\u001b[0m \u001b[43msys\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexit\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "\u001b[0;31mSystemExit\u001b[0m: 1",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "    \u001b[0;31m[... skipping hidden 1 frame]\u001b[0m\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2145\u001b[0m, in \u001b[0;36mInteractiveShell.showtraceback\u001b[0;34m(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\u001b[0m\n\u001b[1;32m   2142\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m exception_only:\n\u001b[1;32m   2143\u001b[0m     stb \u001b[38;5;241m=\u001b[39m [\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mAn exception has occurred, use \u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mtb to see \u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m   2144\u001b[0m            \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mthe full traceback.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m'\u001b[39m]\n\u001b[0;32m-> 2145\u001b[0m     stb\u001b[38;5;241m.\u001b[39mextend(\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mInteractiveTB\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_exception_only\u001b[49m\u001b[43m(\u001b[49m\u001b[43metype\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   2146\u001b[0m \u001b[43m                                                     \u001b[49m\u001b[43mvalue\u001b[49m\u001b[43m)\u001b[49m)\n\u001b[1;32m   2147\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   2149\u001b[0m     \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mcontains_exceptiongroup\u001b[39m(val):\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/IPython/core/ultratb.py:710\u001b[0m, in \u001b[0;36mListTB.get_exception_only\u001b[0;34m(self, etype, value)\u001b[0m\n\u001b[1;32m    702\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mget_exception_only\u001b[39m(\u001b[38;5;28mself\u001b[39m, etype, value):\n\u001b[1;32m    703\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Only print the exception type and message, without a traceback.\u001b[39;00m\n\u001b[1;32m    704\u001b[0m \n\u001b[1;32m    705\u001b[0m \u001b[38;5;124;03m    Parameters\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    708\u001b[0m \u001b[38;5;124;03m    value : exception value\u001b[39;00m\n\u001b[1;32m    709\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m--> 710\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mListTB\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstructured_traceback\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43metype\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvalue\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/IPython/core/ultratb.py:568\u001b[0m, in \u001b[0;36mListTB.structured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, context)\u001b[0m\n\u001b[1;32m    565\u001b[0m     chained_exc_ids\u001b[38;5;241m.\u001b[39madd(\u001b[38;5;28mid\u001b[39m(exception[\u001b[38;5;241m1\u001b[39m]))\n\u001b[1;32m    566\u001b[0m     chained_exceptions_tb_offset \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[1;32m    567\u001b[0m     out_list \u001b[38;5;241m=\u001b[39m (\n\u001b[0;32m--> 568\u001b[0m         \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstructured_traceback\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    569\u001b[0m \u001b[43m            \u001b[49m\u001b[43metype\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    570\u001b[0m \u001b[43m            \u001b[49m\u001b[43mevalue\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    571\u001b[0m \u001b[43m            \u001b[49m\u001b[43m(\u001b[49m\u001b[43metb\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mchained_exc_ids\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m  \u001b[49m\u001b[38;5;66;43;03m# type: ignore\u001b[39;49;00m\n\u001b[1;32m    572\u001b[0m \u001b[43m            \u001b[49m\u001b[43mchained_exceptions_tb_offset\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    573\u001b[0m \u001b[43m            \u001b[49m\u001b[43mcontext\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    574\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    575\u001b[0m         \u001b[38;5;241m+\u001b[39m chained_exception_message\n\u001b[1;32m    576\u001b[0m         \u001b[38;5;241m+\u001b[39m out_list)\n\u001b[1;32m    578\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m out_list\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/IPython/core/ultratb.py:1454\u001b[0m, in \u001b[0;36mAutoFormattedTB.structured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1452\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   1453\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtb \u001b[38;5;241m=\u001b[39m etb\n\u001b[0;32m-> 1454\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mFormattedTB\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstructured_traceback\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1455\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43metype\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mevalue\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43metb\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtb_offset\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mnumber_of_lines_of_context\u001b[49m\n\u001b[1;32m   1456\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/IPython/core/ultratb.py:1345\u001b[0m, in \u001b[0;36mFormattedTB.structured_traceback\u001b[0;34m(self, etype, value, tb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1342\u001b[0m mode \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmode\n\u001b[1;32m   1343\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m mode \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mverbose_modes:\n\u001b[1;32m   1344\u001b[0m     \u001b[38;5;66;03m# Verbose modes need a full traceback\u001b[39;00m\n\u001b[0;32m-> 1345\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mVerboseTB\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstructured_traceback\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1346\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43metype\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mvalue\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtb\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtb_offset\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mnumber_of_lines_of_context\u001b[49m\n\u001b[1;32m   1347\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1348\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m mode \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mMinimal\u001b[39m\u001b[38;5;124m'\u001b[39m:\n\u001b[1;32m   1349\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m ListTB\u001b[38;5;241m.\u001b[39mget_exception_only(\u001b[38;5;28mself\u001b[39m, etype, value)\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/IPython/core/ultratb.py:1192\u001b[0m, in \u001b[0;36mVerboseTB.structured_traceback\u001b[0;34m(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)\u001b[0m\n\u001b[1;32m   1183\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mstructured_traceback\u001b[39m(\n\u001b[1;32m   1184\u001b[0m     \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m   1185\u001b[0m     etype: \u001b[38;5;28mtype\u001b[39m,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1189\u001b[0m     number_of_lines_of_context: \u001b[38;5;28mint\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m5\u001b[39m,\n\u001b[1;32m   1190\u001b[0m ):\n\u001b[1;32m   1191\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Return a nice text document describing the traceback.\"\"\"\u001b[39;00m\n\u001b[0;32m-> 1192\u001b[0m     formatted_exception \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mformat_exception_as_a_whole\u001b[49m\u001b[43m(\u001b[49m\u001b[43metype\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mevalue\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43metb\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mnumber_of_lines_of_context\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m   1193\u001b[0m \u001b[43m                                                           \u001b[49m\u001b[43mtb_offset\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1195\u001b[0m     colors \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mColors  \u001b[38;5;66;03m# just a shorthand + quicker name lookup\u001b[39;00m\n\u001b[1;32m   1196\u001b[0m     colorsnormal \u001b[38;5;241m=\u001b[39m colors\u001b[38;5;241m.\u001b[39mNormal  \u001b[38;5;66;03m# used a lot\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/IPython/core/ultratb.py:1082\u001b[0m, in \u001b[0;36mVerboseTB.format_exception_as_a_whole\u001b[0;34m(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)\u001b[0m\n\u001b[1;32m   1079\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(tb_offset, \u001b[38;5;28mint\u001b[39m)\n\u001b[1;32m   1080\u001b[0m head \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mprepare_header(\u001b[38;5;28mstr\u001b[39m(etype), \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mlong_header)\n\u001b[1;32m   1081\u001b[0m records \u001b[38;5;241m=\u001b[39m (\n\u001b[0;32m-> 1082\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_records\u001b[49m\u001b[43m(\u001b[49m\u001b[43metb\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mnumber_of_lines_of_context\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtb_offset\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;28;01mif\u001b[39;00m etb \u001b[38;5;28;01melse\u001b[39;00m []\n\u001b[1;32m   1083\u001b[0m )\n\u001b[1;32m   1085\u001b[0m frames \u001b[38;5;241m=\u001b[39m []\n\u001b[1;32m   1086\u001b[0m skipped \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n",
      "File \u001b[0;32m~/miniconda3/envs/salt_env/lib/python3.10/site-packages/IPython/core/ultratb.py:1150\u001b[0m, in \u001b[0;36mVerboseTB.get_records\u001b[0;34m(self, etb, number_of_lines_of_context, tb_offset)\u001b[0m\n\u001b[1;32m   1148\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m cf \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m   1149\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m-> 1150\u001b[0m         mod \u001b[38;5;241m=\u001b[39m inspect\u001b[38;5;241m.\u001b[39mgetmodule(\u001b[43mcf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtb_frame\u001b[49m)\n\u001b[1;32m   1151\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m mod \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m   1152\u001b[0m             mod_name \u001b[38;5;241m=\u001b[39m mod\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'tuple' object has no attribute 'tb_frame'"
     ]
    }
   ],
   "source": [
    "from haddock3.src.haddock.clis import cli\n",
    "from build_config import build_config\n",
    "\n",
    "motif_specs = \"[10-40/C24-51/10-40]\"\n",
    "residue_specs = [[463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492]]\n",
    "\n",
    "out_dir = 'run_test'\n",
    "config_file = '/home/mubale/functional_eval/docking/configs/docking-protein-protein-test.cfg'\n",
    "ambig_file = \"configs/ambig_fname.tbl\"\n",
    "molecules = ['/home/xchen/projects/salt/results_rfdiffusion_motif_20241018230935/designability_eval/designs/rf_design_0.pdb', '/home/mubale/functional_eval/docking/configs/8hgo.pdb']\n",
    "\n",
    "cfg = build_config(out_dir, config_file, ambig_file, molecules, motif_specs, residue_specs)\n",
    "cli.main(workflow = config_file)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "salt_env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
